version: '3.8'

services:
  server:
    image: jangrarajat/english-learning-app:v1
    container_name: english-app-server
    ports:
      - "8000:8000"
    volumes:
      - english-app:/app/data
    environment:
      - MONGO_URI=mongodb+srv://rajatjangra9694:TH5YJubpJMBZ7OvT@clusterone.axu2z4n.mongodb.net/verb-challenge
      - JWT_SECRET=your_jwt_secret_key_here_change_in_production
      - CLIENT_URL=http://localhost:5173
      - NODE_ENV=development
    networks:
      - english-app

volumes:
  english-app:

networks:
  english-app:
    driver: bridge