export const verbs = [
  // Day 1
  { v1: 'be', v2: 'was/were', v3: 'been', meaning: 'hona', pronunciation: 'biː',
    examples: { present: 'I am a student.', past: 'I was a student.', perfect: 'I have been a student.' },
    hindiTranslations: { present: 'Main student hoon.', past: 'Main student tha.', perfect: 'Main student raha hoon.' },
    day: 1 },
  { v1: 'have', v2: 'had', v3: 'had', meaning: 'paas hona / rakhna', pronunciation: 'hæv',
    examples: { present: 'I have a car.', past: 'I had a car.', perfect: 'I have had a car.' },
    hindiTranslations: { present: 'Mere paas car hai.', past: 'Mere paas car thi.', perfect: 'Mere paas car rahi hai.' },
    day: 1 },
  { v1: 'do', v2: 'did', v3: 'done', meaning: 'karna', pronunciation: 'duː',
    examples: { present: 'I do my homework.', past: 'I did my homework.', perfect: 'I have done my homework.' },
    hindiTranslations: { present: 'Main apna homework karta hoon.', past: 'Mainne apna homework kiya.', perfect: 'Mainne apna homework kar liya hai.' },
    day: 1 },
  { v1: 'go', v2: 'went', v3: 'gone', meaning: 'jaana', pronunciation: 'ɡoʊ',
    examples: { present: 'I go to school.', past: 'I went to school.', perfect: 'I have gone to school.' },
    hindiTranslations: { present: 'Main school jaata hoon.', past: 'Main school gaya.', perfect: 'Main school gaya hoon.' },
    day: 1 },
  { v1: 'come', v2: 'came', v3: 'come', meaning: 'aana', pronunciation: 'kʌm',
    examples: { present: 'I come home.', past: 'I came home.', perfect: 'I have come home.' },
    hindiTranslations: { present: 'Main ghar aata hoon.', past: 'Main ghar aaya.', perfect: 'Main ghar aaya hoon.' },
    day: 1 },
  
  // Day 2
  { v1: 'get', v2: 'got', v3: 'got/gotten', meaning: 'paana / milna', pronunciation: 'ɡɛt',
    examples: { present: 'I get a gift.', past: 'I got a gift.', perfect: 'I have gotten a gift.' },
    hindiTranslations: { present: 'Mujhe gift milta hai.', past: 'Mujhe gift mila.', perfect: 'Mujhe gift mila hai.' },
    day: 2 },
  { v1: 'make', v2: 'made', v3: 'made', meaning: 'banana', pronunciation: 'meɪk',
    examples: { present: 'I make food.', past: 'I made food.', perfect: 'I have made food.' },
    hindiTranslations: { present: 'Main khana banata hoon.', past: 'Mainne khana banaya.', perfect: 'Mainne khana banaya hai.' },
    day: 2 },
  { v1: 'take', v2: 'took', v3: 'taken', meaning: 'lena', pronunciation: 'teɪk',
    examples: { present: 'I take a book.', past: 'I took a book.', perfect: 'I have taken a book.' },
    hindiTranslations: { present: 'Main kitaab leta hoon.', past: 'Mainne kitaab li.', perfect: 'Mainne kitaab li hai.' },
    day: 2 },
  { v1: 'give', v2: 'gave', v3: 'given', meaning: 'dena', pronunciation: 'ɡɪv',
    examples: { present: 'I give a gift.', past: 'I gave a gift.', perfect: 'I have given a gift.' },
    hindiTranslations: { present: 'Main gift deta hoon.', past: 'Mainne gift diya.', perfect: 'Mainne gift diya hai.' },
    day: 2 },
  { v1: 'know', v2: 'knew', v3: 'known', meaning: 'jaanna', pronunciation: 'noʊ',
    examples: { present: 'I know the answer.', past: 'I knew the answer.', perfect: 'I have known the answer.' },
    hindiTranslations: { present: 'Main jawab jaanta hoon.', past: 'Main jawab jaanta tha.', perfect: 'Main jawab jaanta hoon.' },
    day: 2 },
  
  // Day 3
  { v1: 'think', v2: 'thought', v3: 'thought', meaning: 'sochna', pronunciation: 'θɪŋk',
    examples: { present: 'I think about you.', past: 'I thought about you.', perfect: 'I have thought about you.' },
    hindiTranslations: { present: 'Main tumhare baare mein sochta hoon.', past: 'Mainne tumhare baare mein socha.', perfect: 'Mainne tumhare baare mein socha hai.' },
    day: 3 },
  { v1: 'see', v2: 'saw', v3: 'seen', meaning: 'dekhna', pronunciation: 'siː',
    examples: { present: 'I see a bird.', past: 'I saw a bird.', perfect: 'I have seen a bird.' },
    hindiTranslations: { present: 'Main ek chidiya dekhta hoon.', past: 'Mainne ek chidiya dekhi.', perfect: 'Mainne ek chidiya dekhi hai.' },
    day: 3 },
  { v1: 'look', v2: 'looked', v3: 'looked', meaning: 'dekhna', pronunciation: 'lʊk',
    examples: { present: 'I look at the sky.', past: 'I looked at the sky.', perfect: 'I have looked at the sky.' },
    hindiTranslations: { present: 'Main aasmaan dekhta hoon.', past: 'Mainne aasmaan dekha.', perfect: 'Mainne aasmaan dekha hai.' },
    day: 3 },
  { v1: 'want', v2: 'wanted', v3: 'wanted', meaning: 'chahna', pronunciation: 'wɒnt',
    examples: { present: 'I want water.', past: 'I wanted water.', perfect: 'I have wanted water.' },
    hindiTranslations: { present: 'Mujhe paani chahiye.', past: 'Mujhe paani chahiye tha.', perfect: 'Mujhe paani chahiye raha hai.' },
    day: 3 },
  { v1: 'need', v2: 'needed', v3: 'needed', meaning: 'zaroorat hona', pronunciation: 'niːd',
    examples: { present: 'I need help.', past: 'I needed help.', perfect: 'I have needed help.' },
    hindiTranslations: { present: 'Mujhe madad ki zaroorat hai.', past: 'Mujhe madad ki zaroorat thi.', perfect: 'Mujhe madad ki zaroorat rahi hai.' },
    day: 3 },
  
  // Day 4
  { v1: 'use', v2: 'used', v3: 'used', meaning: 'istemal karna', pronunciation: 'juːz',
    examples: { present: 'I use a phone.', past: 'I used a phone.', perfect: 'I have used a phone.' },
    hindiTranslations: { present: 'Main phone istemal karta hoon.', past: 'Mainne phone istemal kiya.', perfect: 'Mainne phone istemal kiya hai.' },
    day: 4 },
  { v1: 'find', v2: 'found', v3: 'found', meaning: 'dhoondhna / paana', pronunciation: 'faɪnd',
    examples: { present: 'I find my keys.', past: 'I found my keys.', perfect: 'I have found my keys.' },
    hindiTranslations: { present: 'Mujhe meri chabiyan milti hain.', past: 'Mujhe meri chabiyan mili.', perfect: 'Mujhe meri chabiyan mili hain.' },
    day: 4 },
  { v1: 'tell', v2: 'told', v3: 'told', meaning: 'batana', pronunciation: 'tɛl',
    examples: { present: 'I tell a story.', past: 'I told a story.', perfect: 'I have told a story.' },
    hindiTranslations: { present: 'Main kahani sunata hoon.', past: 'Mainne kahani sunayi.', perfect: 'Mainne kahani sunayi hai.' },
    day: 4 },
  { v1: 'ask', v2: 'asked', v3: 'asked', meaning: 'poochhna', pronunciation: 'æsk',
    examples: { present: 'I ask a question.', past: 'I asked a question.', perfect: 'I have asked a question.' },
    hindiTranslations: { present: 'Main sawal poochhta hoon.', past: 'Mainne sawal poochha.', perfect: 'Mainne sawal poochha hai.' },
    day: 4 },
  { v1: 'say', v2: 'said', v3: 'said', meaning: 'kehna', pronunciation: 'seɪ',
    examples: { present: 'I say hello.', past: 'I said hello.', perfect: 'I have said hello.' },
    hindiTranslations: { present: 'Main namaste kehta hoon.', past: 'Mainne namaste kaha.', perfect: 'Mainne namaste kaha hai.' },
    day: 4 },
  
  // Day 5
  { v1: 'work', v2: 'worked', v3: 'worked', meaning: 'kaam karna', pronunciation: 'wɜːrk',
    examples: { present: 'I work hard.', past: 'I worked hard.', perfect: 'I have worked hard.' },
    hindiTranslations: { present: 'Main mehnat karta hoon.', past: 'Mainne mehnat ki.', perfect: 'Mainne mehnat ki hai.' },
    day: 5 },
  { v1: 'call', v2: 'called', v3: 'called', meaning: 'phone karna / bulana', pronunciation: 'kɔːl',
    examples: { present: 'I call my friend.', past: 'I called my friend.', perfect: 'I have called my friend.' },
    hindiTranslations: { present: 'Main apne dost ko phone karta hoon.', past: 'Mainne apne dost ko phone kiya.', perfect: 'Mainne apne dost ko phone kiya hai.' },
    day: 5 },
  { v1: 'try', v2: 'tried', v3: 'tried', meaning: 'koshish karna', pronunciation: 'traɪ',
    examples: { present: 'I try to learn.', past: 'I tried to learn.', perfect: 'I have tried to learn.' },
    hindiTranslations: { present: 'Main seekhne ki koshish karta hoon.', past: 'Mainne seekhne ki koshish ki.', perfect: 'Mainne seekhne ki koshish ki hai.' },
    day: 5 },
  { v1: 'feel', v2: 'felt', v3: 'felt', meaning: 'mehsoos karna', pronunciation: 'fiːl',
    examples: { present: 'I feel happy.', past: 'I felt happy.', perfect: 'I have felt happy.' },
    hindiTranslations: { present: 'Main khush mehsoos karta hoon.', past: 'Main khush mehsoos kiya.', perfect: 'Main khush mehsoos kiya hai.' },
    day: 5 },
  { v1: 'become', v2: 'became', v3: 'become', meaning: 'banna', pronunciation: 'bɪˈkʌm',
    examples: { present: 'I become a teacher.', past: 'I became a teacher.', perfect: 'I have become a teacher.' },
    hindiTranslations: { present: 'Main teacher banta hoon.', past: 'Main teacher bana.', perfect: 'Main teacher ban gaya hoon.' },
    day: 5 },
  
  // Day 6
  { v1: 'leave', v2: 'left', v3: 'left', meaning: 'chhodna / jaana', pronunciation: 'liːv',
    examples: { present: 'I leave at 8 AM.', past: 'I left at 8 AM.', perfect: 'I have left at 8 AM.' },
    hindiTranslations: { present: 'Main subah 8 baje jaata hoon.', past: 'Main subah 8 baje gaya.', perfect: 'Main subah 8 baje gaya hoon.' },
    day: 6 },
  { v1: 'put', v2: 'put', v3: 'put', meaning: 'rakhna', pronunciation: 'pʊt',
    examples: { present: 'I put the book here.', past: 'I put the book here.', perfect: 'I have put the book here.' },
    hindiTranslations: { present: 'Main kitaab yahan rakhta hoon.', past: 'Mainne kitaab yahan rakhi.', perfect: 'Mainne kitaab yahan rakhi hai.' },
    day: 6 },
  { v1: 'keep', v2: 'kept', v3: 'kept', meaning: 'rakhna / banaye rakhna', pronunciation: 'kiːp',
    examples: { present: 'I keep my room clean.', past: 'I kept my room clean.', perfect: 'I have kept my room clean.' },
    hindiTranslations: { present: 'Main apna kamra saaf rakhta hoon.', past: 'Mainne apna kamra saaf rakha.', perfect: 'Mainne apna kamra saaf rakha hai.' },
    day: 6 },
  { v1: 'let', v2: 'let', v3: 'let', meaning: 'anumati dena', pronunciation: 'lɛt',
    examples: { present: 'I let him go.', past: 'I let him go.', perfect: 'I have let him go.' },
    hindiTranslations: { present: 'Main use jaane deta hoon.', past: 'Mainne use jaane diya.', perfect: 'Mainne use jaane diya hai.' },
    day: 6 },
  { v1: 'begin', v2: 'began', v3: 'begun', meaning: 'shuru karna', pronunciation: 'bɪˈɡɪn',
    examples: { present: 'I begin the work.', past: 'I began the work.', perfect: 'I have begun the work.' },
    hindiTranslations: { present: 'Main kaam shuru karta hoon.', past: 'Mainne kaam shuru kiya.', perfect: 'Mainne kaam shuru kar diya hai.' },
    day: 6 },
  
  // Day 8
  { v1: 'seem', v2: 'seemed', v3: 'seemed', meaning: 'lagna / prateet hona', pronunciation: 'siːm',
    examples: { present: 'It seems good.', past: 'It seemed good.', perfect: 'It has seemed good.' },
    hindiTranslations: { present: 'Yeh achha lagta hai.', past: 'Yeh achha laga.', perfect: 'Yeh achha laga hai.' },
    day: 8 },
  { v1: 'help', v2: 'helped', v3: 'helped', meaning: 'madad karna', pronunciation: 'hɛlp',
    examples: { present: 'I help my mother.', past: 'I helped my mother.', perfect: 'I have helped my mother.' },
    hindiTranslations: { present: 'Main apni maa ki madad karta hoon.', past: 'Mainne apni maa ki madad ki.', perfect: 'Mainne apni maa ki madad ki hai.' },
    day: 8 },
  { v1: 'talk', v2: 'talked', v3: 'talked', meaning: 'baat karna', pronunciation: 'tɔːk',
    examples: { present: 'I talk to my friend.', past: 'I talked to my friend.', perfect: 'I have talked to my friend.' },
    hindiTranslations: { present: 'Main apne dost se baat karta hoon.', past: 'Mainne apne dost se baat ki.', perfect: 'Mainne apne dost se baat ki hai.' },
    day: 8 },
  { v1: 'turn', v2: 'turned', v3: 'turned', meaning: 'mudna / badalna', pronunciation: 'tɜːrn',
    examples: { present: 'I turn left.', past: 'I turned left.', perfect: 'I have turned left.' },
    hindiTranslations: { present: 'Main left mudta hoon.', past: 'Main left muda.', perfect: 'Main left muda hoon.' },
    day: 8 },
  { v1: 'start', v2: 'started', v3: 'started', meaning: 'shuru karna', pronunciation: 'stɑːrt',
    examples: { present: 'I start the car.', past: 'I started the car.', perfect: 'I have started the car.' },
    hindiTranslations: { present: 'Main car shuru karta hoon.', past: 'Mainne car shuru ki.', perfect: 'Mainne car shuru ki hai.' },
    day: 8 },
  
  // Day 9
  { v1: 'show', v2: 'showed', v3: 'shown/showed', meaning: 'dikhana', pronunciation: 'ʃoʊ',
    examples: { present: 'I show my ticket.', past: 'I showed my ticket.', perfect: 'I have shown my ticket.' },
    hindiTranslations: { present: 'Main apna ticket dikhata hoon.', past: 'Mainne apna ticket dikhaya.', perfect: 'Mainne apna ticket dikhaya hai.' },
    day: 9 },
  { v1: 'hear', v2: 'heard', v3: 'heard', meaning: 'sunna', pronunciation: 'hɪər',
    examples: { present: 'I hear a song.', past: 'I heard a song.', perfect: 'I have heard a song.' },
    hindiTranslations: { present: 'Main ek gaana sunta hoon.', past: 'Mainne ek gaana suna.', perfect: 'Mainne ek gaana suna hai.' },
    day: 9 },
  { v1: 'play', v2: 'played', v3: 'played', meaning: 'khelna / bajana', pronunciation: 'pleɪ',
    examples: { present: 'I play cricket.', past: 'I played cricket.', perfect: 'I have played cricket.' },
    hindiTranslations: { present: 'Main cricket khelta hoon.', past: 'Mainne cricket khela.', perfect: 'Mainne cricket khela hai.' },
    day: 9 },
  { v1: 'run', v2: 'ran', v3: 'run', meaning: 'daudna / chalana', pronunciation: 'rʌn',
    examples: { present: 'I run fast.', past: 'I ran fast.', perfect: 'I have run fast.' },
    hindiTranslations: { present: 'Main tez daudta hoon.', past: 'Main tez dauda.', perfect: 'Main tez dauda hoon.' },
    day: 9 },
  { v1: 'move', v2: 'moved', v3: 'moved', meaning: 'hilna / sthan badalna', pronunciation: 'muːv',
    examples: { present: 'I move the chair.', past: 'I moved the chair.', perfect: 'I have moved the chair.' },
    hindiTranslations: { present: 'Main kursi hilata hoon.', past: 'Mainne kursi hilai.', perfect: 'Mainne kursi hilai hai.' },
    day: 9 },
  
  // Day 10
  { v1: 'live', v2: 'lived', v3: 'lived', meaning: 'rehna / jeena', pronunciation: 'lɪv',
    examples: { present: 'I live in Delhi.', past: 'I lived in Delhi.', perfect: 'I have lived in Delhi.' },
    hindiTranslations: { present: 'Main Dilli mein rehta hoon.', past: 'Main Dilli mein rehta tha.', perfect: 'Main Dilli mein reh chuka hoon.' },
    day: 10 },
  { v1: 'believe', v2: 'believed', v3: 'believed', meaning: 'vishwas karna', pronunciation: 'bɪˈliːv',
    examples: { present: 'I believe you.', past: 'I believed you.', perfect: 'I have believed you.' },
    hindiTranslations: { present: 'Main tum par vishwas karta hoon.', past: 'Mainne tum par vishwas kiya.', perfect: 'Mainne tum par vishwas kiya hai.' },
    day: 10 },
  { v1: 'bring', v2: 'brought', v3: 'brought', meaning: 'lana', pronunciation: 'brɪŋ',
    examples: { present: 'I bring water.', past: 'I brought water.', perfect: 'I have brought water.' },
    hindiTranslations: { present: 'Main paani laata hoon.', past: 'Main paani laaya.', perfect: 'Main paani laaya hoon.' },
    day: 10 },
  { v1: 'happen', v2: 'happened', v3: 'happened', meaning: 'hona / ghatit hona', pronunciation: 'ˈhæpən',
    examples: { present: 'What happens?', past: 'What happened?', perfect: 'What has happened?' },
    hindiTranslations: { present: 'Kya hota hai?', past: 'Kya hua?', perfect: 'Kya hua hai?' },
    day: 10 },
  { v1: 'write', v2: 'wrote', v3: 'written', meaning: 'likhna', pronunciation: 'raɪt',
    examples: { present: 'I write a letter.', past: 'I wrote a letter.', perfect: 'I have written a letter.' },
    hindiTranslations: { present: 'Main khat likhta hoon.', past: 'Mainne khat likha.', perfect: 'Mainne khat likha hai.' },
    day: 10 },
  
  // Day 11
  { v1: 'provide', v2: 'provided', v3: 'provided', meaning: 'pradan karna / dena', pronunciation: 'prəˈvaɪd',
    examples: { present: 'I provide support.', past: 'I provided support.', perfect: 'I have provided support.' },
    hindiTranslations: { present: 'Main sahayata pradan karta hoon.', past: 'Mainne sahayata pradan ki.', perfect: 'Mainne sahayata pradan ki hai.' },
    day: 11 },
  { v1: 'sit', v2: 'sat', v3: 'sat', meaning: 'baithna', pronunciation: 'sɪt',
    examples: { present: 'I sit here.', past: 'I sat here.', perfect: 'I have sat here.' },
    hindiTranslations: { present: 'Main yahan baithta hoon.', past: 'Main yahan baitha.', perfect: 'Main yahan baitha hoon.' },
    day: 11 },
  { v1: 'stand', v2: 'stood', v3: 'stood', meaning: 'khada hona', pronunciation: 'stænd',
    examples: { present: 'I stand there.', past: 'I stood there.', perfect: 'I have stood there.' },
    hindiTranslations: { present: 'Main wahan khada hota hoon.', past: 'Main wahan khada tha.', perfect: 'Main wahan khada hoon.' },
    day: 11 },
  { v1: 'lose', v2: 'lost', v3: 'lost', meaning: 'khona / haarna', pronunciation: 'luːz',
    examples: { present: 'I lose my keys.', past: 'I lost my keys.', perfect: 'I have lost my keys.' },
    hindiTranslations: { present: 'Mujhe meri chabiyan kho jati hain.', past: 'Mujhe meri chabiyan kho gayi.', perfect: 'Mujhe meri chabiyan kho gayi hain.' },
    day: 11 },
  { v1: 'pay', v2: 'paid', v3: 'paid', meaning: 'bhugtan karna', pronunciation: 'peɪ',
    examples: { present: 'I pay the bill.', past: 'I paid the bill.', perfect: 'I have paid the bill.' },
    hindiTranslations: { present: 'Main bill bhugtaan karta hoon.', past: 'Mainne bill bhugtaan kiya.', perfect: 'Mainne bill bhugtaan kiya hai.' },
    day: 11 },
  
  // Day 12
  { v1: 'meet', v2: 'met', v3: 'met', meaning: 'milna', pronunciation: 'miːt',
    examples: { present: 'I meet my friend.', past: 'I met my friend.', perfect: 'I have met my friend.' },
    hindiTranslations: { present: 'Main apne dost se milta hoon.', past: 'Main apne dost se mila.', perfect: 'Main apne dost se mila hoon.' },
    day: 12 },
  { v1: 'include', v2: 'included', v3: 'included', meaning: 'shamil karna', pronunciation: 'ɪnˈkluːd',
    examples: { present: 'I include everyone.', past: 'I included everyone.', perfect: 'I have included everyone.' },
    hindiTranslations: { present: 'Main sabko shamil karta hoon.', past: 'Mainne sabko shamil kiya.', perfect: 'Mainne sabko shamil kiya hai.' },
    day: 12 },
  { v1: 'continue', v2: 'continued', v3: 'continued', meaning: 'jaari rakhna', pronunciation: 'kənˈtɪnjuː',
    examples: { present: 'I continue my work.', past: 'I continued my work.', perfect: 'I have continued my work.' },
    hindiTranslations: { present: 'Main apna kaam jaari rakhta hoon.', past: 'Mainne apna kaam jaari rakha.', perfect: 'Mainne apna kaam jaari rakha hai.' },
    day: 12 },
  { v1: 'set', v2: 'set', v3: 'set', meaning: 'set karna / rakhna', pronunciation: 'sɛt',
    examples: { present: 'I set the table.', past: 'I set the table.', perfect: 'I have set the table.' },
    hindiTranslations: { present: 'Main table set karta hoon.', past: 'Mainne table set kiya.', perfect: 'Mainne table set kiya hai.' },
    day: 12 },
  { v1: 'learn', v2: 'learned/learnt', v3: 'learned/learnt', meaning: 'seekhna', pronunciation: 'lɜːrn',
    examples: { present: 'I learn English.', past: 'I learned English.', perfect: 'I have learned English.' },
    hindiTranslations: { present: 'Main English seekhta hoon.', past: 'Mainne English seekhi.', perfect: 'Mainne English seekhi hai.' },
    day: 12 },
  
  // Day 13
  { v1: 'change', v2: 'changed', v3: 'changed', meaning: 'badalna', pronunciation: 'tʃeɪndʒ',
    examples: { present: 'I change my dress.', past: 'I changed my dress.', perfect: 'I have changed my dress.' },
    hindiTranslations: { present: 'Main apna kapda badalta hoon.', past: 'Mainne apna kapda badala.', perfect: 'Mainne apna kapda badal liya hai.' },
    day: 13 },
  { v1: 'lead', v2: 'led', v3: 'led', meaning: 'netritva karna / le jaana', pronunciation: 'liːd',
    examples: { present: 'I lead the team.', past: 'I led the team.', perfect: 'I have led the team.' },
    hindiTranslations: { present: 'Main team ka netritva karta hoon.', past: 'Mainne team ka netritva kiya.', perfect: 'Mainne team ka netritva kiya hai.' },
    day: 13 },
  { v1: 'understand', v2: 'understood', v3: 'understood', meaning: 'samajhna', pronunciation: 'ˌʌndərˈstænd',
    examples: { present: 'I understand you.', past: 'I understood you.', perfect: 'I have understood you.' },
    hindiTranslations: { present: 'Main tumhe samajhta hoon.', past: 'Mainne tumhe samjha.', perfect: 'Mainne tumhe samajh liya hai.' },
    day: 13 },
  { v1: 'watch', v2: 'watched', v3: 'watched', meaning: 'dekhna / nazar rakhna', pronunciation: 'wɒtʃ',
    examples: { present: 'I watch TV.', past: 'I watched TV.', perfect: 'I have watched TV.' },
    hindiTranslations: { present: 'Main TV dekhta hoon.', past: 'Mainne TV dekha.', perfect: 'Mainne TV dekha hai.' },
    day: 13 },
  { v1: 'follow', v2: 'followed', v3: 'followed', meaning: 'follow karna', pronunciation: 'ˈfɒloʊ',
    examples: { present: 'I follow the rules.', past: 'I followed the rules.', perfect: 'I have followed the rules.' },
    hindiTranslations: { present: 'Main rules follow karta hoon.', past: 'Mainne rules follow kiye.', perfect: 'Mainne rules follow kiye hain.' },
    day: 13 },
  
  // Day 15
  { v1: 'stop', v2: 'stopped', v3: 'stopped', meaning: 'rokna / rukna', pronunciation: 'stɒp',
    examples: { present: 'I stop the car.', past: 'I stopped the car.', perfect: 'I have stopped the car.' },
    hindiTranslations: { present: 'Main car rokt a hoon.', past: 'Mainne car roki.', perfect: 'Mainne car rok li hai.' },
    day: 15 },
  { v1: 'create', v2: 'created', v3: 'created', meaning: 'banana / rachna', pronunciation: 'kriˈeɪt',
    examples: { present: 'I create art.', past: 'I created art.', perfect: 'I have created art.' },
    hindiTranslations: { present: 'Main kala banata hoon.', past: 'Mainne kala banayi.', perfect: 'Mainne kala banayi hai.' },
    day: 15 },
  { v1: 'speak', v2: 'spoke', v3: 'spoken', meaning: 'bolna', pronunciation: 'spiːk',
    examples: { present: 'I speak English.', past: 'I spoke English.', perfect: 'I have spoken English.' },
    hindiTranslations: { present: 'Main English bolta hoon.', past: 'Mainne English boli.', perfect: 'Mainne English boli hai.' },
    day: 15 },
  { v1: 'read', v2: 'read', v3: 'read', meaning: 'padhna', pronunciation: 'riːd',
    examples: { present: 'I read a book.', past: 'I read a book.', perfect: 'I have read a book.' },
    hindiTranslations: { present: 'Main kitaab padhta hoon.', past: 'Mainne kitaab padhi.', perfect: 'Mainne kitaab padh li hai.' },
    day: 15 },
  { v1: 'allow', v2: 'allowed', v3: 'allowed', meaning: 'anumati dena', pronunciation: 'əˈlaʊ',
    examples: { present: 'I allow it.', past: 'I allowed it.', perfect: 'I have allowed it.' },
    hindiTranslations: { present: 'Main iski anumati deta hoon.', past: 'Mainne iski anumati di.', perfect: 'Mainne iski anumati di hai.' },
    day: 15 },
  
  // Day 16
  { v1: 'add', v2: 'added', v3: 'added', meaning: 'jodna', pronunciation: 'æd',
    examples: { present: 'I add sugar.', past: 'I added sugar.', perfect: 'I have added sugar.' },
    hindiTranslations: { present: 'Main cheeni milata hoon.', past: 'Mainne cheeni milayi.', perfect: 'Mainne cheeni mila di hai.' },
    day: 16 },
  { v1: 'spend', v2: 'spent', v3: 'spent', meaning: 'kharch karna / samay bitana', pronunciation: 'spɛnd',
    examples: { present: 'I spend money.', past: 'I spent money.', perfect: 'I have spent money.' },
    hindiTranslations: { present: 'Main paisa kharch karta hoon.', past: 'Mainne paisa kharch kiya.', perfect: 'Mainne paisa kharch kiya hai.' },
    day: 16 },
  { v1: 'grow', v2: 'grew', v3: 'grown', meaning: 'badhna / ugna', pronunciation: 'ɡroʊ',
    examples: { present: 'I grow plants.', past: 'I grew plants.', perfect: 'I have grown plants.' },
    hindiTranslations: { present: 'Main paudhe ugata hoon.', past: 'Mainne paudhe ugaye.', perfect: 'Mainne paudhe ugaye hain.' },
    day: 16 },
  { v1: 'open', v2: 'opened', v3: 'opened', meaning: 'kholna', pronunciation: 'ˈoʊpən',
    examples: { present: 'I open the door.', past: 'I opened the door.', perfect: 'I have opened the door.' },
    hindiTranslations: { present: 'Main darwaza kholta hoon.', past: 'Mainne darwaza khola.', perfect: 'Mainne darwaza khol diya hai.' },
    day: 16 },
  { v1: 'walk', v2: 'walked', v3: 'walked', meaning: 'chalna', pronunciation: 'wɔːk',
    examples: { present: 'I walk to school.', past: 'I walked to school.', perfect: 'I have walked to school.' },
    hindiTranslations: { present: 'Main school tak chal kar jaata hoon.', past: 'Main school tak chal kar gaya.', perfect: 'Main school tak chal kar gaya hoon.' },
    day: 16 },
  
  // Day 17
  { v1: 'win', v2: 'won', v3: 'won', meaning: 'jeetna', pronunciation: 'wɪn',
    examples: { present: 'I win the game.', past: 'I won the game.', perfect: 'I have won the game.' },
    hindiTranslations: { present: 'Main game jeet ta hoon.', past: 'Mainne game jeeti.', perfect: 'Mainne game jeet li hai.' },
    day: 17 },
  { v1: 'offer', v2: 'offered', v3: 'offered', meaning: 'pesh karna', pronunciation: 'ˈɔːfər',
    examples: { present: 'I offer help.', past: 'I offered help.', perfect: 'I have offered help.' },
    hindiTranslations: { present: 'Main madad pesh karta hoon.', past: 'Mainne madad pesh ki.', perfect: 'Mainne madad pesh ki hai.' },
    day: 17 },
  { v1: 'remember', v2: 'remembered', v3: 'remembered', meaning: 'yaad rakhna', pronunciation: 'rɪˈmɛmbər',
    examples: { present: 'I remember you.', past: 'I remembered you.', perfect: 'I have remembered you.' },
    hindiTranslations: { present: 'Main tumhe yaad rakhta hoon.', past: 'Mainne tumhe yaad rakha.', perfect: 'Mainne tumhe yaad rakha hai.' },
    day: 17 },
  { v1: 'love', v2: 'loved', v3: 'loved', meaning: 'pyaar karna', pronunciation: 'lʌv',
    examples: { present: 'I love you.', past: 'I loved you.', perfect: 'I have loved you.' },
    hindiTranslations: { present: 'Main tumse pyaar karta hoon.', past: 'Mainne tumse pyaar kiya.', perfect: 'Mainne tumse pyaar kiya hai.' },
    day: 17 },
  { v1: 'consider', v2: 'considered', v3: 'considered', meaning: 'vichar karna', pronunciation: 'kənˈsɪdər',
    examples: { present: 'I consider it.', past: 'I considered it.', perfect: 'I have considered it.' },
    hindiTranslations: { present: 'Main is par vichar karta hoon.', past: 'Mainne is par vichar kiya.', perfect: 'Mainne is par vichar kiya hai.' },
    day: 17 },
  
  // Day 18
  { v1: 'appear', v2: 'appeared', v3: 'appeared', meaning: 'dikhai dena / prakat hona', pronunciation: 'əˈpɪər',
    examples: { present: 'It appears here.', past: 'It appeared here.', perfect: 'It has appeared here.' },
    hindiTranslations: { present: 'Yeh yahan dikhai deta hai.', past: 'Yeh yahan dikhai diya.', perfect: 'Yeh yahan dikhai diya hai.' },
    day: 18 },
  { v1: 'buy', v2: 'bought', v3: 'bought', meaning: 'khareedna', pronunciation: 'baɪ',
    examples: { present: 'I buy a gift.', past: 'I bought a gift.', perfect: 'I have bought a gift.' },
    hindiTranslations: { present: 'Main gift khareedta hoon.', past: 'Mainne gift khareeda.', perfect: 'Mainne gift khareed liya hai.' },
    day: 18 },
  { v1: 'wait', v2: 'waited', v3: 'waited', meaning: 'intezar karna', pronunciation: 'weɪt',
    examples: { present: 'I wait for you.', past: 'I waited for you.', perfect: 'I have waited for you.' },
    hindiTranslations: { present: 'Main tumhara intezaar karta hoon.', past: 'Mainne tumhara intezaar kiya.', perfect: 'Mainne tumhara intezaar kiya hai.' },
    day: 18 },
  { v1: 'serve', v2: 'served', v3: 'served', meaning: 'seva karna / parosna', pronunciation: 'sɜːrv',
    examples: { present: 'I serve food.', past: 'I served food.', perfect: 'I have served food.' },
    hindiTranslations: { present: 'Main khana paros ta hoon.', past: 'Mainne khana parosa.', perfect: 'Mainne khana paros diya hai.' },
    day: 18 },
  { v1: 'die', v2: 'died', v3: 'died', meaning: 'marna', pronunciation: 'daɪ',
    examples: { present: 'The flower dies.', past: 'The flower died.', perfect: 'The flower has died.' },
    hindiTranslations: { present: 'Phool mar jata hai.', past: 'Phool mar gaya.', perfect: 'Phool mar gaya hai.' },
    day: 18 },
  
  // Day 19
  { v1: 'send', v2: 'sent', v3: 'sent', meaning: 'bhejna', pronunciation: 'sɛnd',
    examples: { present: 'I send a message.', past: 'I sent a message.', perfect: 'I have sent a message.' },
    hindiTranslations: { present: 'Main message bhejta hoon.', past: 'Mainne message bheja.', perfect: 'Mainne message bhej diya hai.' },
    day: 19 },
  { v1: 'expect', v2: 'expected', v3: 'expected', meaning: 'ummeed karna', pronunciation: 'ɪkˈspɛkt',
    examples: { present: 'I expect you.', past: 'I expected you.', perfect: 'I have expected you.' },
    hindiTranslations: { present: 'Main tumse ummeed karta hoon.', past: 'Mainne tumse ummeed ki.', perfect: 'Mainne tumse ummeed ki hai.' },
    day: 19 },
  { v1: 'build', v2: 'built', v3: 'built', meaning: 'banana / nirman karna', pronunciation: 'bɪld',
    examples: { present: 'I build a house.', past: 'I built a house.', perfect: 'I have built a house.' },
    hindiTranslations: { present: 'Main ghar banata hoon.', past: 'Mainne ghar banaya.', perfect: 'Mainne ghar bana liya hai.' },
    day: 19 },
  { v1: 'stay', v2: 'stayed', v3: 'stayed', meaning: 'rehna / thaharna', pronunciation: 'steɪ',
    examples: { present: 'I stay here.', past: 'I stayed here.', perfect: 'I have stayed here.' },
    hindiTranslations: { present: 'Main yahan rehta hoon.', past: 'Main yahan raha.', perfect: 'Main yahan raha hoon.' },
    day: 19 },
  { v1: 'fall', v2: 'fell', v3: 'fallen', meaning: 'girna', pronunciation: 'fɔːl',
    examples: { present: 'I fall down.', past: 'I fell down.', perfect: 'I have fallen down.' },
    hindiTranslations: { present: 'Main gir jaata hoon.', past: 'Main gir gaya.', perfect: 'Main gir gaya hoon.' },
    day: 19 },
  
  // Day 20
  { v1: 'cut', v2: 'cut', v3: 'cut', meaning: 'kaatna', pronunciation: 'kʌt',
    examples: { present: 'I cut the bread.', past: 'I cut the bread.', perfect: 'I have cut the bread.' },
    hindiTranslations: { present: 'Main bread kaat ta hoon.', past: 'Mainne bread kaata.', perfect: 'Mainne bread kaat liya hai.' },
    day: 20 },
  { v1: 'reach', v2: 'reached', v3: 'reached', meaning: 'pahunchna', pronunciation: 'riːtʃ',
    examples: { present: 'I reach home.', past: 'I reached home.', perfect: 'I have reached home.' },
    hindiTranslations: { present: 'Main ghar pahunch ta hoon.', past: 'Main ghar pahuncha.', perfect: 'Main ghar pahunch gaya hoon.' },
    day: 20 },
  { v1: 'kill', v2: 'killed', v3: 'killed', meaning: 'maarna', pronunciation: 'kɪl',
    examples: { present: 'I kill the mosquito.', past: 'I killed the mosquito.', perfect: 'I have killed the mosquito.' },
    hindiTranslations: { present: 'Main machar maarta hoon.', past: 'Mainne machar maara.', perfect: 'Mainne machar maar diya hai.' },
    day: 20 },
  { v1: 'remain', v2: 'remained', v3: 'remained', meaning: 'bane rehna', pronunciation: 'rɪˈmeɪn',
    examples: { present: 'I remain here.', past: 'I remained here.', perfect: 'I have remained here.' },
    hindiTranslations: { present: 'Main yahan bana rehta hoon.', past: 'Main yahan bana raha.', perfect: 'Main yahan bana raha hoon.' },
    day: 20 },
  { v1: 'suggest', v2: 'suggested', v3: 'suggested', meaning: 'sujhav dena', pronunciation: 'səˈdʒɛst',
    examples: { present: 'I suggest this.', past: 'I suggested this.', perfect: 'I have suggested this.' },
    hindiTranslations: { present: 'Main yeh sujhav deta hoon.', past: 'Mainne yeh sujhav diya.', perfect: 'Mainne yeh sujhav diya hai.' },
    day: 20 },
  
  // Day 22
  { v1: 'raise', v2: 'raised', v3: 'raised', meaning: 'uthana / badhana', pronunciation: 'reɪz',
    examples: { present: 'I raise my hand.', past: 'I raised my hand.', perfect: 'I have raised my hand.' },
    hindiTranslations: { present: 'Main apna haath uthata hoon.', past: 'Mainne apna haath uthaya.', perfect: 'Mainne apna haath uthaya hai.' },
    day: 22 },
  { v1: 'pass', v2: 'passed', v3: 'passed', meaning: 'guzarna / pass karna', pronunciation: 'pæs',
    examples: { present: 'I pass the exam.', past: 'I passed the exam.', perfect: 'I have passed the exam.' },
    hindiTranslations: { present: 'Main exam pass karta hoon.', past: 'Mainne exam pass kiya.', perfect: 'Mainne exam pass kar liya hai.' },
    day: 22 },
  { v1: 'sell', v2: 'sold', v3: 'sold', meaning: 'bechna', pronunciation: 'sɛl',
    examples: { present: 'I sell books.', past: 'I sold books.', perfect: 'I have sold books.' },
    hindiTranslations: { present: 'Main kitaabein bechta hoon.', past: 'Mainne kitaabein bechi.', perfect: 'Mainne kitaabein bechi hain.' },
    day: 22 },
  { v1: 'require', v2: 'required', v3: 'required', meaning: 'aavashyakta hona', pronunciation: 'rɪˈkwaɪər',
    examples: { present: 'I require help.', past: 'I required help.', perfect: 'I have required help.' },
    hindiTranslations: { present: 'Mujhe madad ki aavashyakta hai.', past: 'Mujhe madad ki aavashyakta thi.', perfect: 'Mujhe madad ki aavashyakta rahi hai.' },
    day: 22 },
  { v1: 'report', v2: 'reported', v3: 'reported', meaning: 'report karna / batana', pronunciation: 'rɪˈpɔːrt',
    examples: { present: 'I report the news.', past: 'I reported the news.', perfect: 'I have reported the news.' },
    hindiTranslations: { present: 'Main khabar report karta hoon.', past: 'Mainne khabar report ki.', perfect: 'Mainne khabar report ki hai.' },
    day: 22 },
  
  // Day 23
  { v1: 'decide', v2: 'decided', v3: 'decided', meaning: 'nirnay lena', pronunciation: 'dɪˈsaɪd',
    examples: { present: 'I decide now.', past: 'I decided now.', perfect: 'I have decided now.' },
    hindiTranslations: { present: 'Main ab nirnay leta hoon.', past: 'Mainne ab nirnay liya.', perfect: 'Mainne ab nirnay le liya hai.' },
    day: 23 },
  { v1: 'pull', v2: 'pulled', v3: 'pulled', meaning: 'kheenchna', pronunciation: 'pʊl',
    examples: { present: 'I pull the rope.', past: 'I pulled the rope.', perfect: 'I have pulled the rope.' },
    hindiTranslations: { present: 'Main rassi kheenchta hoon.', past: 'Mainne rassi kheechi.', perfect: 'Mainne rassi kheech li hai.' },
    day: 23 },
  { v1: 'return', v2: 'returned', v3: 'returned', meaning: 'lautna / wapas karna', pronunciation: 'rɪˈtɜːrn',
    examples: { present: 'I return home.', past: 'I returned home.', perfect: 'I have returned home.' },
    hindiTranslations: { present: 'Main ghar lautta hoon.', past: 'Main ghar laut aaya.', perfect: 'Main ghar laut aaya hoon.' },
    day: 23 },
  { v1: 'explain', v2: 'explained', v3: 'explained', meaning: 'samjhana', pronunciation: 'ɪkˈspleɪn',
    examples: { present: 'I explain clearly.', past: 'I explained clearly.', perfect: 'I have explained clearly.' },
    hindiTranslations: { present: 'Main saaf samjhaata hoon.', past: 'Mainne saaf samjhaaya.', perfect: 'Mainne saaf samjha diya hai.' },
    day: 23 },
  { v1: 'hope', v2: 'hoped', v3: 'hoped', meaning: 'aasha karna', pronunciation: 'hoʊp',
    examples: { present: 'I hope so.', past: 'I hoped so.', perfect: 'I have hoped so.' },
    hindiTranslations: { present: 'Main aasha karta hoon.', past: 'Mainne aasha ki.', perfect: 'Mainne aasha ki hai.' },
    day: 23 },
  
  // Day 24
  { v1: 'develop', v2: 'developed', v3: 'developed', meaning: 'vikasit karna', pronunciation: 'dɪˈvɛləp',
    examples: { present: 'I develop skills.', past: 'I developed skills.', perfect: 'I have developed skills.' },
    hindiTranslations: { present: 'Main kaushal vikasit karta hoon.', past: 'Mainne kaushal vikasit kiye.', perfect: 'Mainne kaushal vikasit kar liye hain.' },
    day: 24 },
  { v1: 'carry', v2: 'carried', v3: 'carried', meaning: 'le jaana / uthana', pronunciation: 'ˈkæri',
    examples: { present: 'I carry a bag.', past: 'I carried a bag.', perfect: 'I have carried a bag.' },
    hindiTranslations: { present: 'Main bag le jaata hoon.', past: 'Mainne bag le jaaya.', perfect: 'Mainne bag le jaaya hai.' },
    day: 24 },
  { v1: 'break', v2: 'broke', v3: 'broken', meaning: 'todna', pronunciation: 'breɪk',
    examples: { present: 'I break the glass.', past: 'I broke the glass.', perfect: 'I have broken the glass.' },
    hindiTranslations: { present: 'Main glass todta hoon.', past: 'Mainne glass toda.', perfect: 'Mainne glass tod diya hai.' },
    day: 24 },
  { v1: 'receive', v2: 'received', v3: 'received', meaning: 'prapt karna', pronunciation: 'rɪˈsiːv',
    examples: { present: 'I receive a gift.', past: 'I received a gift.', perfect: 'I have received a gift.' },
    hindiTranslations: { present: 'Mujhe gift prapt hota hai.', past: 'Mujhe gift prapt hua.', perfect: 'Mujhe gift prapt ho gaya hai.' },
    day: 24 },
  { v1: 'agree', v2: 'agreed', v3: 'agreed', meaning: 'sahmat hona', pronunciation: 'əˈɡriː',
    examples: { present: 'I agree with you.', past: 'I agreed with you.', perfect: 'I have agreed with you.' },
    hindiTranslations: { present: 'Main tumse sahmat hoon.', past: 'Main tumse sahmat tha.', perfect: 'Main tumse sahmat ho gaya hoon.' },
    day: 24 },
  
  // Day 25
  { v1: 'support', v2: 'supported', v3: 'supported', meaning: 'samarthan karna', pronunciation: 'səˈpɔːrt',
    examples: { present: 'I support the team.', past: 'I supported the team.', perfect: 'I have supported the team.' },
    hindiTranslations: { present: 'Main team ka samarthan karta hoon.', past: 'Mainne team ka samarthan kiya.', perfect: 'Mainne team ka samarthan kiya hai.' },
    day: 25 },
  { v1: 'hit', v2: 'hit', v3: 'hit', meaning: 'maarna / takrana', pronunciation: 'hɪt',
    examples: { present: 'I hit the ball.', past: 'I hit the ball.', perfect: 'I have hit the ball.' },
    hindiTranslations: { present: 'Main ball maarta hoon.', past: 'Mainne ball maara.', perfect: 'Mainne ball maar diya hai.' },
    day: 25 },
  { v1: 'produce', v2: 'produced', v3: 'produced', meaning: 'utpadan karna / banana', pronunciation: 'prəˈduːs',
    examples: { present: 'I produce music.', past: 'I produced music.', perfect: 'I have produced music.' },
    hindiTranslations: { present: 'Main music produce karta hoon.', past: 'Mainne music produce kiya.', perfect: 'Mainne music produce kiya hai.' },
    day: 25 },
  { v1: 'eat', v2: 'ate', v3: 'eaten', meaning: 'khaana', pronunciation: 'iːt',
    examples: { present: 'I eat food.', past: 'I ate food.', perfect: 'I have eaten food.' },
    hindiTranslations: { present: 'Main khana khaata hoon.', past: 'Mainne khana khaya.', perfect: 'Mainne khana kha liya hai.' },
    day: 25 },
  { v1: 'catch', v2: 'caught', v3: 'caught', meaning: 'pakadna', pronunciation: 'kætʃ',
    examples: { present: 'I catch the ball.', past: 'I caught the ball.', perfect: 'I have caught the ball.' },
    hindiTranslations: { present: 'Main ball pakadta hoon.', past: 'Mainne ball pakda.', perfect: 'Mainne ball pakad liya hai.' },
    day: 25 },
  
  // Day 26
  { v1: 'draw', v2: 'drew', v3: 'drawn', meaning: 'kheenchna / chitra banana', pronunciation: 'drɔː',
    examples: { present: 'I draw a picture.', past: 'I drew a picture.', perfect: 'I have drawn a picture.' },
    hindiTranslations: { present: 'Main chitra banata hoon.', past: 'Mainne chitra banaya.', perfect: 'Mainne chitra bana liya hai.' },
    day: 26 },
  { v1: 'choose', v2: 'chose', v3: 'chosen', meaning: 'chunna', pronunciation: 'tʃuːz',
    examples: { present: 'I choose this.', past: 'I chose this.', perfect: 'I have chosen this.' },
    hindiTranslations: { present: 'Main yeh chunta hoon.', past: 'Mainne yeh chuna.', perfect: 'Mainne yeh chun liya hai.' },
    day: 26 },
  { v1: 'cause', v2: 'caused', v3: 'caused', meaning: 'kaaran banna / karna', pronunciation: 'kɔːz',
    examples: { present: 'This causes problems.', past: 'This caused problems.', perfect: 'This has caused problems.' },
    hindiTranslations: { present: 'Yeh samasyaayein paida karta hai.', past: 'Isne samasyaayein paida ki.', perfect: 'Isne samasyaayein paida ki hain.' },
    day: 26 },
  { v1: 'point', v2: 'pointed', v3: 'pointed', meaning: 'ishara karna', pronunciation: 'pɔɪnt',
    examples: { present: 'I point there.', past: 'I pointed there.', perfect: 'I have pointed there.' },
    hindiTranslations: { present: 'Main wahan ishara karta hoon.', past: 'Mainne wahan ishara kiya.', perfect: 'Mainne wahan ishara kiya hai.' },
    day: 26 },
  { v1: 'listen', v2: 'listened', v3: 'listened', meaning: 'dhyaan se sunna', pronunciation: 'ˈlɪsən',
    examples: { present: 'I listen to music.', past: 'I listened to music.', perfect: 'I have listened to music.' },
    hindiTranslations: { present: 'Main dhyaan se music sunta hoon.', past: 'Mainne dhyaan se music suna.', perfect: 'Mainne dhyaan se music sun liya hai.' },
    day: 26 },
  
  // Day 27
  { v1: 'realize', v2: 'realized', v3: 'realized', meaning: 'ehsaas hona / samajh jaana', pronunciation: 'ˈriːəlaɪz',
    examples: { present: 'I realize it now.', past: 'I realized it then.', perfect: 'I have realized it.' },
    hindiTranslations: { present: 'Mujhe ab ehsaas hua.', past: 'Mujhe tab ehsaas hua.', perfect: 'Mujhe ehsaas ho gaya hai.' },
    day: 27 },
  { v1: 'place', v2: 'placed', v3: 'placed', meaning: 'rakhna', pronunciation: 'pleɪs',
    examples: { present: 'I place it here.', past: 'I placed it here.', perfect: 'I have placed it here.' },
    hindiTranslations: { present: 'Main ise yahan rakhta hoon.', past: 'Mainne ise yahan rakha.', perfect: 'Mainne ise yahan rakh diya hai.' },
    day: 27 },
  { v1: 'close', v2: 'closed', v3: 'closed', meaning: 'band karna', pronunciation: 'kloʊz',
    examples: { present: 'I close the door.', past: 'I closed the door.', perfect: 'I have closed the door.' },
    hindiTranslations: { present: 'Main darwaza band karta hoon.', past: 'Mainne darwaza band kiya.', perfect: 'Mainne darwaza band kar diya hai.' },
    day: 27 },
  { v1: 'involve', v2: 'involved', v3: 'involved', meaning: 'shamil karna / hona', pronunciation: 'ɪnˈvɒlv',
    examples: { present: 'I involve everyone.', past: 'I involved everyone.', perfect: 'I have involved everyone.' },
    hindiTranslations: { present: 'Main sabko shamil karta hoon.', past: 'Mainne sabko shamil kiya.', perfect: 'Mainne sabko shamil kar liya hai.' },
    day: 27 },
  { v1: 'accept', v2: 'accepted', v3: 'accepted', meaning: 'sweekar karna', pronunciation: 'əkˈsɛpt',
    examples: { present: 'I accept the offer.', past: 'I accepted the offer.', perfect: 'I have accepted the offer.' },
    hindiTranslations: { present: 'Main offer sweekar karta hoon.', past: 'Mainne offer sweekar kiya.', perfect: 'Mainne offer sweekar kar liya hai.' },
    day: 27 }
];